"""
English to Katakana Converter for IT/Tech News TTS
Comprehensive dictionary for AI, programming, cloud, and tech company terms
"""
import re
from typing import Dict, Optional

# =============================================================================
# COMPREHENSIVE DICTIONARY FOR IT NEWS
# =============================================================================
COMMON_WORDS: Dict[str, str] = {
    # ========================================================================
    # PEOPLE NAMES - Tech Industry Leaders
    # ========================================================================
    # AI/ML Leaders
    "moxie": "モキシー",
    "musk": "マスク",
    "elon": "イーロン",
    "sam": "サム",
    "simon": "サイモン",
    "willison": "ウィリスン",
    "wilson": "ウィルソン",
    "lin": "リン",
    "ozaki": "オザキ",
    "altman": "オルトマン",
    "satya": "サティア",
    "nadella": "ナデラ",
    "jensen": "イェンセン",
    "huang": "ファン",
    "demis": "デミス",
    "hassabis": "ハサビス",
    "marlinspike": "マーリンスパイク",
    "zuckerberg": "ザッカーバーグ",
    "cook": "クック",
    "tim": "ティム",
    "bill": "ビル",
    "gates": "ゲイツ",
    "steve": "スティーブ",
    "jobs": "ジョブズ",
    "wozniak": "ウォズニアック",
    "ballmer": "バルマー",
    "page": "ペイジ",
    "larry": "ラリー",
    "sergey": "セルゲイ",
    "brin": "ブリン",
    "sundar": "スンダー",
    "pichai": "ピチャイ",
    "bezos": "ベゾス",
    "jassy": "ジャシー",
    "hastings": "ヘイスティングス",
    "dorsey": "ドーシー",
    "jack": "ジャック",
    "spiegel": "シュピーゲル",
    "ek": "エク",
    "daniel": "ダニエル",
    "kai": "カイ",
    "rene": "レネ",
    "fried": "フリード",
    "collison": "コリソン",
    "patrick": "パトリック",
    "john": "ジョン",
    "hashicorp": "ハシコープ",

    # ========================================================================
    # TECH COMPANIES - Major & Startups
    # ========================================================================
    "nvidia": "エヌビディア",
    "openai": "オープンエーアイ",
    "anthropic": "アンソロピック",
    "google": "グーグル",
    "microsoft": "マイクロソフト",
    "amazon": "アマゾン",
    "meta": "メタ",
    "apple": "アップル",
    "tesla": "テスラ",
    "spacex": "スペースエックス",
    "twitter": "ツイッター",
    "x": "エックス",
    "facebook": "フェイスブック",
    "instagram": "インスタグラム",
    "whatsapp": "ワッツアップ",
    "tiktok": "ティックトック",
    "alibaba": "アリババ",
    "tencent": "テンセント",
    "baidu": "バイドゥ",
    "samsung": "サムスン",
    "lg": "エルジー",
    "intel": "インテル",
    "amd": "エーエムディー",
    "qualcomm": "クアルコム",
    "sony": "ソニー",
    "nintendo": "ニンテンドー",
    "netflix": "ネットフリックス",
    "spotify": "スポティファイ",
    "uber": "ウーバー",
    "lyft": "リフト",
    "airbnb": "エアビーアンドビー",
    "stripe": "ストライプ",
    "shopify": "ショピファイ",
    "square": "スクエア",
    "paypal": "ペイパル",
    "adobe": "アドビ",
    "oracle": "オラクル",
    "salesforce": "セールスフォース",
    "sap": "エスエイピー",
    "ibm": "アイビーエム",
    "redhat": "レッドハット",
    "canonical": "カノニカル",
    "vmware": "ブイエムウェア",
    "citrix": "シトリックス",
    "cisco": "シスコ",
    "juniper": "ジュニパー",
    "palo": "パロ",
    "alto": "アルト",
    "fortinet": "フォーティネット",
    "checkpoint": "チェックポイント",
    "crowdstrike": "クラウドストライク",
    "snowflake": "スノーフレイク",
    "databricks": "データブリックス",
    "mongodb": "モンゴディービー",
    "redis": "レディス",
    "elastic": "エラスティック",
    "confluent": "コンフルエント",
    "hashicorp": "ハシコープ",
    "terraform": "テラフォーム",
    "vault": "ボールト",
    "consul": "コンサル",
    "kubernetes": "クバネティス",
    "docker": "ドッカー",
    "github": "ギットハブ",
    "gitlab": "ギットラボ",
    "bitbucket": "ビットバケット",
    "atlassian": "アトラシアン",
    "jira": "ジラ",
    "confluence": "コンフルエンス",
    "notion": "ノーション",
    "slack": "スラック",
    "cursor": "カーソル",
    "vscode": "ブイエスコード",
    "vs": "ブイエス",
    "code": "コード",
    "discord": "ディスコード",
    "zoom": "ズーム",
    "teams": "チームス",
    "figma": "フィグマ",
    "canva": "キャンバ",
    "adsk": "オートデスク",
    "autodesk": "オートデスク",
    "unity": "ユニティ",
    "unreal": "アンリアル",
    "epic": "エピック",
    "games": "ゲームズ",

    # ========================================================================
    # AI/ML TERMS - Comprehensive
    # ========================================================================
    "artificial": "アーティフィシャル",
    "intelligence": "インテリジェンス",
    "machine": "マシン",
    "deep": "ディープ",
    "learning": "ラーニング",
    "reinforcement": "強化",
    "supervised": "スーパーバイズド",
    "unsupervised": "アンスーパーバイズド",
    "transformer": "トランスフォーマー",
    "attention": "アテンション",
    "parameter": "パラメータ",
    "training": "トレーニング",
    "inference": "インファレンス",
    "fine": "ファイン",
    "tuning": "チューニング",
    "prompt": "プロンプト",
    "completion": "コンプリート",
    "token": "トークン",
    "embedding": "エンベディング",
    "vector": "ベクター",
    "model": "モデル",
    "weights": "ウェイト",
    "bias": "バイアス",
    "gradient": "グラディエント",
    "optimizer": "オプティマイザー",
    "loss": "ロス",
    "accuracy": "アキュラシー",
    "precision": "プレシジョン",
    "recall": "リコール",
    "f1": "エフワン",
    "neural": "ニューラル",
    "network": "ネットワーク",
    "perceptron": "パーセプトロン",
    "backpropagation": "バックプロパゲーション",
    "convolutional": "コンボルーショナル",
    "recurrent": "カレント",
    "lstm": "エルエスティーエム",
    "gan": "ガン",
    "diffusion": "ディフュージョン",
    "stable": "ステーブル",
    "midjourney": "ミッドジャーニー",
    "dall": "ダル",
    "claude": "クロード",
    "gemini": "ジェミニ",
    "gpt": "ジーピーティー",
    "bert": "バート",
    "roberta": "ロバータ",
    "t5": "ティーファイブ",
    "llama": "ラマ",
    "mistral": "ミストラル",
    "mixtral": "ミクストラル",
    "phi": "ファイ",
    "orca": "オルカ",
    "chatgpt": "チャットジーピーティー",
    "copilot": "コパイロット",
    "huggingface": "ハッギングフェイス",
    "langchain": "ラングチェイン",
    "llamaindex": "ラマインデックス",
    "pinecone": "パインコーン",
    "weaviate": "ウェイビエート",
    "chromadb": "クロームディービー",
    "milvus": "ミルバス",
    "rag": "ラグ",
    "agent": "エージェント",
    "multimodal": "マルチモーダル",
    "vision": "ビジョン",
    "speech": "スピーチ",
    "nlp": "エヌエルピー",
    "cv": "コンピュータビジョン",
    "generative": "ジェネレーティブ",
    "discriminative": "ディスクリミネイティブ",

    # ========================================================================
    # PROGRAMMING LANGUAGES & FRAMEWORKS
    # ========================================================================
    "python": "パイソン",
    "javascript": "ジャバスクリプト",
    "typescript": "タイプスクリプト",
    "java": "ジャバ",
    "kotlin": "コトリン",
    "swift": "スイフト",
    "objective": "オブジェクティブ",
    "rust": "ラスト",
    "go": "ゴーラング",
    "golang": "ゴーラング",
    "c++": "シープラスプラス",
    "csharp": "シーシャープ",
    "ruby": "ルビー",
    "php": "ピーエイチピー",
    "scala": "スカラ",
    "clojure": "クロージャー",
    "haskell": "ハスケル",
    "erlang": "アーラン",
    "elixir": "エリクサー",
    "julia": "ジュリア",
    "matlab": "マットラブ",
    "r": "アール",
    "sql": "エスキューエル",
    "nosql": "ノーエスキューエル",
    "graphql": "グラフキューエル",
    "html": "エイチティーエムエル",
    "css": "シーエスエス",
    "xml": "エックスエムエル",
    "json": "ジェイソン",
    "yaml": "ヤメル",
    "toml": "トムル",
    "markdown": "マークダウン",
    "latex": "ラテックス",
    "react": "リアクト",
    "vue": "ビュー",
    "angular": "アンギュラー",
    "svelte": "スベルト",
    "next": "ネクスト",
    "nuxt": "ヌークスト",
    "node": "ノード",
    "express": "エクスプレス",
    "nestjs": "ネストジェーエス",
    "django": "ジャンゴ",
    "flask": "フラスク",
    "fastapi": "ファストエーピーアイ",
    "spring": "スプリング",
    "rails": "レイルズ",
    "laravel": "ララベル",
    "fiber": "ファイバー",
    "echo": "エコー",
    "gin": "ジン",
    "actix": "アクティックス",
    "rocket": "ロケット",
    "flutter": "フラッター",
    "reactnative": "リアクトネイティブ",
    "electron": "エレクトロン",
    "tauri": "タウリ",
    "qt": "キューティー",
    "gtk": "ジーティーケー",

    # ========================================================================
    # CLOUD & INFRASTRUCTURE
    # ========================================================================
    "aws": "アマゾンウェブサービス",
    "azure": "アジュール",
    "gcp": "ジーシーピー",
    "ec2": "イーシーツー",
    "s3": "エススリー",
    "lambda": "ラムダ",
    "eks": "イーケーエス",
    "fargate": "ファーゲート",
    "rds": "アールディーエス",
    "dynamodb": "ダイナモ",
    "redshift": "レッドシフト",
    "athena": "アテナ",
    "glue": "グルー",
    "kinesis": "キネシス",
    "cloudfront": "クラウドフロント",
    "route": "ルート",
    "vpc": "ブイピーシー",
    "function": "ファンクション",
    "app": "アップ",
    "service": "サービス",
    "blob": "ブロブ",
    "cosmos": "コスモス",
    "synapse": "シナプス",
    "datafactory": "データファクトリー",
    "datalake": "データレイク",
    "bigquery": "ビッグクエリ",
    "compute": "コンピュート",
    "engine": "エンジン",
    "storage": "ストレージ",
    "firewall": "ファイアウォール",
    "loadbalancer": "ロードバランサー",
    "cdn": "シーディーエヌ",
    "dns": "ディーエヌエス",
    "ssl": "エスエスエル",
    "tls": "ティーエルエス",
    "vpn": "ブイピーエヌ",
    "vpc": "ブイピーシー",
    "subnet": "サブネット",
    "instance": "インスタンス",
    "container": "コンテナ",
    "pod": "ポッド",
    "namespace": "ネームスペース",
    "cluster": "クラスタ",
    "node": "ノード",
    "deployment": "デプロイメント",
    "service": "サービス",
    "ingress": "イングレス",
    "helm": "ヘルム",
    "istio": "イシティオ",
    "envoy": "エンボイ",
    "prometheus": "プロメテウス",
    "grafana": "グラファナ",
    "elasticsearch": "エラスティックサーチ",
    "logstash": "ログスタッシュ",
    "kibana": "キバナ",
    "fluentd": "フルエントディー",
    "jaeger": "イェーガー",
    "zipkin": "ジプキン",
    "terraform": "テラフォーム",
    "ansible": "アンシブル",
    "puppet": "パペット",
    "chef": "シェフ",
    "salt": "ソルト",
    "jenkins": "ジェンキンス",
    "gitlab": "ギットラボ",
    "circleci": "サークルシーアイ",
    "travis": "トラビス",
    "github": "ギットハブ",
    "actions": "アクションズ",
    "vercel": "バーセル",
    "netlify": "ネトリファイ",
    "heroku": "ヘロク",
    "railway": "レールウェイ",

    # ========================================================================
    # SECURITY & COMPLIANCE
    # ========================================================================
    "security": "セキュリティ",
    "privacy": "プライバシー",
    "encryption": "エンクリプション",
    "authentication": "オーセンティケーション",
    "authorization": "オーソリゼーション",
    "oauth": "オーオース",
    "saml": "サム",
    "ldap": "エルダップ",
    "kerberos": "ケルベロス",
    "certificate": "サーティフィケート",
    "key": "キー",
    "malware": "マルウェア",
    "ransomware": "ランサムウェア",
    "phishing": "フィッシング",
    "vulnerability": "ヴルネラビリティ",
    "exploit": "エクスプロイト",
    "breach": "ブリーチ",
    "attack": "アタック",
    "threat": "スレット",
    "intrusion": "イントゥージョン",
    "detection": "ディテクション",
    "prevention": "プリベンション",
    "firewall": "ファイアウォール",
    "ids": "アイディーエス",
    "ips": "アイピーエス",
    "siem": "シエム",
    "soar": "ソアー",
    "edr": "イーディーアール",
    "xdr": "エックスディーアール",
    "mdr": "エムディーアール",
    "zero": "ゼロ",
    "trust": "トラスト",
    "gdpr": "ジェーディーピーアール",
    "hipaa": "ヒパ",
    "pci": "ピーシーアイ",
    "dss": "ディーエスエス",
    "soc": "ソック",
    "audit": "オーディット",
    "compliance": "コンプライアンス",
    "governance": "ガバナンス",
    "risk": "リスク",

    # ========================================================================
    # DEVOPS & CI/CD
    # ========================================================================
    "devops": "デブオプス",
    "cicd": "シーアイシーディー",
    "continuous": "コンティニュアス",
    "integration": "インテグレーション",
    "delivery": "デリバリー",
    "deployment": "デプロイメント",
    "pipeline": "パイプライン",
    "workflow": "ワークフロー",
    "repository": "リポジトリ",
    "branch": "ブランチ",
    "merge": "マージ",
    "pull": "プル",
    "request": "リクエスト",
    "commit": "コミット",
    "push": "プッシュ",
    "clone": "クローン",
    "fork": "フォーク",
    "release": "リリース",
    "version": "バージョン",
    "agile": "アジャイル",
    "scrum": "スクラム",
    "kanban": "カンバン",
    "sprint": "スプリント",
    "standup": "スタンドアップ",
    "retrospective": "レトロスペクティブ",
    "backlog": "バックログ",
    "story": "ストーリー",
    "epic": "エピック",
    "milestone": "マイルストーン",
    "iteration": "イテレーション",

    # ========================================================================
    # DATA & DATABASES
    # ========================================================================
    "database": "データベース",
    "schema": "スキーマ",
    "table": "テーブル",
    "row": "ロウ",
    "column": "カラム",
    "index": "インデックス",
    "query": "クエリ",
    "transaction": "トランザクション",
    "migration": "マイグレーション",
    "seed": "シード",
    "backup": "バックアップ",
    "restore": "リストア",
    "replication": "レプリケーション",
    "sharding": "シャーディング",
    "partitioning": "パーティショニング",
    "acid": "アシッド",
    "base": "ベース",
    "relational": "リレーショナル",
    "document": "ドキュメント",
    "graph": "グラフ",
    "time": "タイム",
    "series": "シリーズ",
    "key": "キー",
    "value": "バリュー",
    "wide": "ワイド",
    "columnar": "カラムナー",
    "warehouse": "ウェアハウス",
    "lake": "レイク",
    "house": "ハウス",
    "lakehouse": "レイクハウス",
    "mesh": "メッシュ",
    "fabric": "ファブリック",
    "catalog": "カタログ",

    # ========================================================================
    # HARDWARE & INFRASTRUCTURE
    # ========================================================================
    "hardware": "ハードウェア",
    "software": "ソフトウェア",
    "firmware": "ファームウェア",
    "middleware": "ミドルウェア",
    "cpu": "シーピーユー",
    "gpu": "ジーピーユー",
    "tpu": "ティーピーユー",
    "npu": "エヌピーユー",
    "fpga": "エフピージーエー",
    "asic": "エイシック",
    "ssd": "エスエスディー",
    "hdd": "エイチディーディー",
    "nvme": "エヌブイエムイー",
    "pcie": "ピーシーアイイー",
    "ethernet": "イーサネット",
    "fiber": "ファイバー",
    "channel": "チャネル",
    "infiniband": "インフィニバンド",
    "rdma": "アールディーエムエー",
    "router": "ルーター",
    "switch": "スイッチ",
    "gateway": "ゲートウェイ",
    "bridge": "ブリッジ",
    "modem": "モデム",
    "access": "アクセス",
    "point": "ポイント",
    "latency": "レイテンシ",
    "bandwidth": "バンドウィズ",
    "throughput": "スループット",
    "iops": "アイオプス",
    "uptime": "アップタイム",
    "downtime": "ダウンタイム",
    "redundancy": "レダンダンシー",
    "availability": "アベイラビリティ",
    "scalability": "スケーラビリティ",
    "reliability": "リアイアビリティ",
    "performance": "パフォーマンス",
    "optimization": "オプティミゼーション",

    # ========================================================================
    # PROTOCOLS & STANDARDS
    # ========================================================================
    "http": "エイチティーティーピー",
    "https": "エイチティーティーピーエス",
    "ftp": "エフティーピー",
    "sftp": "エスエフティーピー",
    "smtp": "エスエムティーピー",
    "pop3": "ポップスリー",
    "imap": "アイマップ",
    "tcp": "ティーシーピー",
    "udp": "ユーディーピー",
    "ip": "アイピー",
    "ipv4": "アイピーブイフォー",
    "ipv6": "アイピーブイシックス",
    "dhcp": "ディーエイチシーピー",
    "nat": "エヌエーティー",
    "pat": "ピーエーティー",
    "icmp": "アイシーエムピー",
    "arp": "エーアールピー",
    "rarp": "アールアールピー",
    "bgp": "ビージーピー",
    "ospf": "オーエスピーエフ",
    "eigrp": "イーアイジーアールピー",
    "rip": "リップ",
    "websocket": "ウェブソケット",
    "grpc": "ジーアールピーシー",
    "rest": "レスト",
    "soap": "ソープ",
    "graphql": "グラフキューエル",
    "webhook": "ウェブフック",
    "mqtt": "エムキューティーティー",
    "amqp": "エーエムキューピー",
    "kafka": "カフカ",
    "rabbitmq": "ラビットキューエム",
    "activemq": "アクティブエムキューユー",
    "redis": "レディス",
    "memcached": "メムキャッシュド",
    "zeromq": "ゼロエムキューユー",
    "nanomsg": "ナノメッセージ",
    "protobuf": "プロトコルバッファ",
    "avro": "アブロ",
    "thrift": "スリフト",
    "flatbuffers": "フラットバッファーズ",

    # ========================================================================
    # BLOCKCHAIN & CRYPTO
    # ========================================================================
    "blockchain": "ブロックチェーン",
    "crypto": "クリプト",
    "bitcoin": "ビットコイン",
    "ethereum": "イーサリアム",
    "solana": "ソラナ",
    "cardano": "カルダノ",
    "polkadot": "ポルカドット",
    "polygon": "ポリゴン",
    "avalanche": "アバランチ",
    "terra": "テラ",
    "bnb": "ビーエヌビー",
    "dogecoin": "ドージコイン",
    "shiba": "シバ",
    "nft": "エフティー",
    "defi": "ディファイ",
    "dao": "ダオ",
    "wallet": "ウォレット",
    "exchange": "エクスチェンジ",
    "mining": "マイニング",
    "staking": "ステーキング",
    "yield": "イールド",
    "farming": "ファーミング",
    "smart": "スマート",
    "contract": "コントラクト",
    "dapp": "ディアプリ",
    "web3": "ウェブスリー",
    "metamask": "メタマスク",
    "opensea": "オープンシー",

    # ========================================================================
    # GENERAL TECH TERMS
    # ========================================================================
    "emulation": "エミュレーション",
    "alternative": "オルタナティブ",
    "algorithm": "アルゴリズム",
    "innovation": "イノベーション",
    "generation": "ジェネレーション",
    "processing": "プロセッシング",
    "computing": "コンピューティング",
    "interface": "インターフェース",
    "platform": "プラットフォーム",
    "framework": "フレームワーク",
    "server": "サーバー",
    "client": "クライアント",
    "browser": "ブラウザ",
    "application": "アプリケーション",
    "virtual": "バーチャル",
    "physical": "フィジカル",
    "digital": "デジタル",
    "analog": "アナログ",
    "quantum": "クォンタム",
    "robotics": "ロボティクス",
    "automation": "オートメーション",
    "assistant": "アシスタント",
    "chatbot": "チャットボット",
    "language": "ランゲージ",
    "translation": "翻訳",
    "transcription": "文字起こし",
    "synthesis": "合成",
    "api": "エーピーアイ",
    "sdk": "エスディーケー",
    "ide": "アイディーイー",
    "ui": "ユーアイ",
    "ux": "ユーエックス",
    "vr": "ブイアール",
    "ar": "エーアール",
    "mr": "ミックスドリアリティ",
    "xr": "エックスアール",
    "iot": "アイオーティー",
    "ai": "エーアイ",
    "agi": "エージーアイ",
    "llm": "エルエルエム",
    "ml": "エムエル",
    "dl": "ディーエル",
    "cv": "コンピュータビジョン",
    "nlp": "エヌエルピー",

    # ========================================================================
    # BUSINESS & STARTUP TERMS
    # ========================================================================
    "revenue": "レベニュー",
    "profit": "プロフィット",
    "investment": "インベストメント",
    "valuation": "バリュエーション",
    "stock": "ストック",
    "share": "シェア",
    "market": "マーケット",
    "economy": "エコノミー",
    "inflation": "インフレーション",
    "recession": "リセッション",
    "growth": "グロース",
    "decline": "ディークライン",
    "merger": "マージャー",
    "acquisition": "アクイジション",
    "partnership": "パートナーシップ",
    "competition": "コンペティション",
    "monopoly": "モノポリー",
    "regulation": "レギュレーション",
    "policy": "ポリシー",
    "lawsuit": "ロースイート",
    "legal": "リーガル",
    "copyright": "コピーライト",
    "patent": "パテント",
    "license": "ライセンス",
    "ipo": "アイピーオー",
    "startup": "スタートアップ",
    "unicorn": "ユニコーン",
    "decacorn": "デカコーン",
    "hectocorn": "ヘクトコーン",
    "venture": "ベンチャー",
    "capital": "キャピタル",
    "angel": "エンジェル",
    "investor": "インベスター",
    "entrepreneur": "アントレプレナー",
    "founder": "ファウンダー",
    "ceo": "シージーオー",
    "cto": "シーティーオー",
    "cfo": "シーエフオー",
    "coo": "シーオーオー",
    "cmo": "シーエムオー",
    "ciso": "シーアイエスオー",
    "board": "ボード",
    "stakeholder": "ステークホルダー",
    "customer": "カスタマー",
    "user": "ユーザー",
    "client": "クライアント",
    "enterprise": "エンタープライズ",
    "sme": "エスエムイー",
    "smb": "エスエムビー",

    # ========================================================================
    # HARDWARE SPECS & FORMATS
    # ========================================================================
    "fp64": "エフピーろくよん",
    "fp32": "エフピーサんに",
    "fp16": "エフピーじゅうろく",
    "bf16": "ビーエフじゅうろく",
    "fp8": "エフピーエイト",
    "int8": "イントエイト",
    "int4": "イントフォー",
    "uint8": "ユイントエイト",
    "x86": "エックスはちじゅうろく",
    "x64": "エックスろくじゅうよん",
    "arm64": "アーアールエムろくじゅうよん",
    "risc": "リスク",
    "v": "ブイ",
    "cisc": "シスク",
    "ram": "ラム",
    "rom": "ロム",
    "dram": "ディーラム",
    "sram": "エスラム",
    "hbm": "エイチビーエム",
    "gddr": "ジーディーディーアール",
    "lpddr": "エルピーディーディーアール",
    "usb": "ユーエスビー",
    "hdmi": "エイチディーエムアイ",
    "displayport": "ディスプレイポート",
    "thunderbolt": "サンダーボルト",
    "lightning": "ライトニング",
    "bluetooth": "ブルートゥース",
    "wifi": "ワイファイ",
    "wlan": "ワイラン",
    "wwan": "ワイワン",
    "5g": "ファイブジー",
    "4g": "フォージー",
    "3g": "スリージー",
    "lte": "エルティーイー",
    "lte": "ロングタームエボリューション",
    "gsm": "ジーエスエム",
    "cdma": "シーディーマエーエム",
    "wcdma": "ダブリューシーディーマエーエム",
    "volte": "ボルテ",
    "nr": "エヌアール",
    "sa": "エスエー",
    "nsa": "エヌエスエー",

    # ========================================================================
    # COMMON WORDS & EXPRESSIONS
    # ========================================================================
    # Articles & prepositions (single letters often used in English)
    "a": "ア",
    "the": "ザ",
    "of": "オブ",
    "in": "イン",
    "on": "オン",
    "at": "アット",
    "to": "トゥ",
    "for": "フォー",
    "with": "ウィズ",
    "from": "フロム",
    "by": "バイ",
    "and": "アンド",
    "or": "オア",
    "as": "アズ",
    "is": "イズ",
    "it": "イット",
    # Common verbs
    "created": "クリエイテッド",
    "focused": "フォーカスト",
    "based": "ベースド",
    "called": "コールド",
    "named": "ネイムド",
    "used": "ユーズド",
    "support": "サポート",
    # Tech terms
    "emulation": "エミュレーション",
    "privacy": "プライバシー",
    "alternative": "オルタナティブ",
    "algorithm": "アルゴリズム",
    "register": "レジスター",
    "software": "ソフトウェア",
    "hardware": "ハードウェア",
    "innovation": "イノベーション",
    "generation": "ジェネレーション",
    "processing": "プロセッシング",
    "computing": "コンピューティング",
    "network": "ネットワーク",
    "automation": "オートメーション",
}


# =============================================================================
# PHONETIC MAPPING FOR FALLBACK
# =============================================================================
PHONETIC_MAP = {
    # Consonants
    'b': 'ブ', 'c': 'ク', 'd': 'ド', 'f': 'フ', 'g': 'グ',
    'h': 'ハ', 'j': 'ジ', 'k': 'ク', 'l': 'ル', 'm': 'ム',
    'n': 'ン', 'p': 'プ', 'q': 'ク', 'r': 'ル', 's': 'ス',
    't': 'ト', 'v': 'ヴ', 'w': 'ウ', 'x': 'ク', 'y': 'イ', 'z': 'ズ',

    # Vowels
    'a': 'ア', 'e': 'エ', 'i': 'イ', 'o': 'オ', 'u': 'ウ',

    # Common combinations
    'ch': 'チ', 'sh': 'シ', 'th': 'サ', 'ph': 'フ',
    'ck': 'ック', 'ng': 'ング', 'rt': 'ルト', 'ld': 'ルド',
    'nt': 'ント', 'st': 'スト', 'sp': 'スポ', 'tr': 'トラ',
    'qu': 'ク', 'xi': 'クシ', 'xe': 'クセ',
}


def convert_english_to_katakana(text: str) -> str:
    """
    Convert English words in text to katakana for TTS pronunciation.

    Preserves Japanese text, only converts sequences of English letters.
    Single letters are kept as-is (likely acronyms handled separately).

    Args:
        text: Mixed Japanese/English text

    Returns:
        Text with English words converted to katakana
    """
    # Pattern to match English words (sequences of letters, at least 1 char)
    # Single letters are now handled (a, the, etc. in dictionary)
    pattern = r'[a-zA-Z]+'

    def replace_word(match):
        word = match.group(0)
        lower_word = word.lower()

        # Check dictionary first
        if lower_word in COMMON_WORDS:
            return COMMON_WORDS[lower_word]

        # For all-uppercase acronyms (like AI, GPU, FP64)
        if word.isupper() and len(word) <= 6:
            # Already handled by dictionary, skip
            return word

        # For capitalized words, try lowercase version
        if word[0].isupper() and len(word) <= 10:
            if lower_word in COMMON_WORDS:
                return COMMON_WORDS[lower_word]

        # Fallback: keep as-is (VOICEVOX will handle it, or add to dictionary later)
        return word

    # Replace English words with katakana equivalents
    result = re.sub(pattern, replace_word, text)

    return result


def preprocess_text_for_tts(text: str) -> str:
    """
    Preprocess text for TTS by converting English words to katakana.
    This is the main function to call from TTS modules.

    Args:
        text: Input text (may contain English words)

    Returns:
        Text with English words converted to katakana for pronunciation
    """
    return convert_english_to_katakana(text)


if __name__ == "__main__":
    # Test
    test_cases = [
        "Moxie Marlinspike created a privacy-focused alternative to ChatGPT.",
        "Nvidia's FP64 emulation is groundbreaking.",
        "Elon Musk and Sam Altman discussed AI safety.",
        "OpenAI released a new model called GPT-5.",
        "Google and Microsoft are competing in the cloud market.",
    ]

    print("=== English to Katakana Conversion Test ===\n")
    for test in test_cases:
        converted = preprocess_text_for_tts(test)
        print(f"Original: {test}")
        print(f"Converted: {converted}")
        print()
